language: c
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - rake
      - bison
      - git
      - gperf
      - libonig-dev
      - mysql-server
      - mysql-client
compiler:
  - gcc
  - clang
before_script:
  - sudo service mysql stop
env:
  - MRUBY_VERSION=1.4.0
  - MRUBY_VERSION=master
script:
  - rake test
