language: c
compiler:
  - gcc
  - clang
before_install:
    - sudo apt-get -qq update
install:
    - sudo apt-get -qq install rake bison git gperf
    - DEBIAN_FRONTEND=noninteractive sudo -E apt-get -qq install mysql-server
script:
  - rake test
