language: c
addons:
  apt:
    packages:
      - rake
      - bison
      - git
      - gperf
      - libonig-dev
compiler:
  - gcc
  - clang
before_script:
  - sudo service mysql stop
env:
  - MRUBY_VERSION=1.3.0
  - MRUBY_VERSION=master
script:
  - rake test
